In [12]:
## Pandas

In [13]:
## NumPy → works with arrays of numbers.
## Pandas → works with tables/spreadsheets of data.

In [14]:
## Pandas : Powerful data manipulation library in Python widely used for data manipulation and data cleaning.
## It provides two primary data structures : Series and Data Frame 
## Series: 1D array like object that can hold any datatype. It is similar to a column in object.
## Data Frame : 2D,multiple rows and columns, size mutable, and potentially 
## heterogeneous tabular data structure with labeled axes ( rows and columns)

In [15]:
import pandas as pd

In [16]:
data = [1,2,3,4,5]
series = pd.Series(data)
print("Series: \n", series)
print(type(series))

Series:
 0    1
1    2
2    3
3    4
4    5
dtype: int64
<class 'pandas.Series'>

In [17]:
## Create a series from Dictionary
data = {'a':1,'b':2,'c':3}
pd.Series(data)

a    1
b    2
c    3
dtype: int64

In [18]:
data = [10,20,30]
index = ['a','b','c']
pd.Series(data,index=index)

a    10
b    20
c    30
dtype: int64

In [18]:
## Create a dataframe from dictionary of list 
data = {
    'Name':['Rose','Jack','Dawson'],
    'age':[19,20,22],
    'City':['Banglore','New York','Los Vegas']
}
df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  age       City
0    Rose   19   Banglore
1    Jack   20   New York
2  Dawson   22  Los Vegas
<class 'pandas.DataFrame'>

In [20]:
import numpy as np
np.array(df)

array([['Rose', 19, 'Banglore'],
       ['Jack', 20, 'New York'],
       ['Dawson', 22, 'Los Vegas']], dtype=object)

In [21]:
## Create a Data Frame from a list of Dictionaries 
data = [
    {'Name':'Rose','age':32, 'City':'Banglore'},
    {'Name':'Jack','age':16, 'City':'Los Vegas'},
    {'Name':'Dawson','age':24, 'City':'New York'},
    {'Name':'Daniel','age':26, 'City':'New York'}
]
df=pd.DataFrame(data)
print(df)
print(type(df))

     Name  age       City
0    Rose   32   Banglore
1    Jack   16  Los Vegas
2  Dawson   24   New York
3  Daniel   26   New York
<class 'pandas.DataFrame'>

In [13]:
## reading the csv file 
df = pd.read_csv('sales_data.csv')
df.head(5)   ## first 5 records

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [14]:
df.tail(5)  ## last 5 records

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
235,10236,2024-08-23,Home Appliances,Nespresso Vertuo Next Coffee and Espresso Maker,1,159.99,159.99,Europe,PayPal
236,10237,2024-08-24,Clothing,Nike Air Force 1 Sneakers,3,90.00,270.00,Asia,Debit Card
237,10238,2024-08-25,Books,The Handmaid's Tale by Margaret Atwood,3,10.99,32.97,North America,Credit Card
238,10239,2024-08-26,Beauty Products,Sunday Riley Luna Sleeping Night Oil,1,55.00,55.00,Europe,PayPal
239,10240,2024-08-27,Sports,Yeti Rambler 20 oz Tumbler,2,29.99,59.98,Asia,Credit Card

In [19]:
## Accessing Data from datafame
df

     Name  age       City
0    Rose   19   Banglore
1    Jack   20   New York
2  Dawson   22  Los Vegas

In [22]:
df['Name']
## o/p: shows 1 coulmn

0      Rose
1      Jack
2    Dawson
Name: Name, dtype: str

In [ ]:
type(df['Name'])
## it actually become a series

In [23]:
df.loc[0]  ## 0th row

Name        Rose
age           19
City    Banglore
Name: 0, dtype: object

In [24]:
##indexloc
df.iloc[0]

Name        Rose
age           19
City    Banglore
Name: 0, dtype: object

In [29]:
df.iloc[0, 0]

'Rose'

In [32]:
df

     Name  age       City
0    Rose   19   Banglore
1    Jack   20   New York
2  Dawson   22  Los Vegas

In [34]:
## Accessing a specified Element
df.at[1,'age']

np.int64(20)

In [35]:
## Accessing a specified Element
df.at[2,'Name']

'Dawson'

In [36]:
## Accessing a specified Element using iat
df.iat[2,2]

'Los Vegas'

In [37]:
## Data Manipulation with DataFrame
df

     Name  age       City
0    Rose   19   Banglore
1    Jack   20   New York
2  Dawson   22  Los Vegas

In [62]:
df['Salary']=[5000,6000,7000]
df

     Name  age       City  Salary
0    Rose   19   Banglore    5000
1    Jack   20   New York    6000
2  Dawson   22  Los Vegas    7000

In [52]:
## df.drop('Salary')  Error: becz by default ur axis value will be zero, which means by default it will be checking in the row index and 
## row index doesnt have a name like 'Salary'

In [55]:
## Remove a Column
df.drop('Salary',axis=1)

     Name  age       City
0    Rose   19   Banglore
1    Jack   20   New York
2  Dawson   22  Los Vegas

In [59]:
df

     Name  age       City
0    Rose   19   Banglore
1    Jack   20   New York
2  Dawson   22  Los Vegas

## not a permanent operation, it is a temporary operation infact it does not even save the state of the dataframe.
## In order to save it

In [63]:
df.drop('Salary',axis=1,inplace=True)

In [61]:
df

     Name  age       City
0    Rose   19   Banglore
1    Jack   20   New York
2  Dawson   22  Los Vegas

In [65]:
## Add age to the column
df['age']=df['age']+1
df

     Name  age       City
0    Rose   20   Banglore
1    Jack   21   New York
2  Dawson   23  Los Vegas

In [67]:
df.drop(0)

     Name  age       City
1    Jack   21   New York
2  Dawson   23  Los Vegas

In [68]:
df

     Name  age       City
0    Rose   20   Banglore
1    Jack   21   New York
2  Dawson   23  Los Vegas

In [69]:
df.drop(0,inplace=True)

In [70]:
df

     Name  age       City
1    Jack   21   New York
2  Dawson   23  Los Vegas

In [74]:
## reading the csv file 
df = pd.read_csv('sales_data.csv')
df.head(5)   ## first 5 records

,Transaction ID,Date,Product Category,Product Name,Units Sold,Unit Price,Total Revenue,Region,Payment Method
0,10001,2024-01-01,Electronics,iPhone 14 Pro,2,999.99,1999.98,North America,Credit Card
1,10002,2024-01-02,Home Appliances,Dyson V11 Vacuum,1,499.99,499.99,Europe,PayPal
2,10003,2024-01-03,Clothing,Levi's 501 Jeans,3,69.99,209.97,Asia,Debit Card
3,10004,2024-01-04,Books,The Da Vinci Code,4,15.99,63.96,North America,Credit Card
4,10005,2024-01-05,Beauty Products,Neutrogena Skincare Set,1,89.99,89.99,Europe,PayPal

In [75]:
# Display the data types of each column
print("Data types:\n", df.dtypes)

# Describe the DataFrame
print("Statistical summary:\n", df.describe())

Data types:
 Transaction ID        int64
Date                    str
Product Category        str
Product Name            str
Units Sold            int64
Unit Price          float64
Total Revenue       float64
Region                  str
Payment Method          str
dtype: object
Statistical summary:
        Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000

In [76]:
df.describe()

       Transaction ID  Units Sold   Unit Price  Total Revenue
count       240.00000  240.000000   240.000000     240.000000
mean      10120.50000    2.158333   236.395583     335.699375
std          69.42622    1.322454   429.446695     485.804469
min       10001.00000    1.000000     6.500000       6.500000
25%       10060.75000    1.000000    29.500000      62.965000
50%       10120.50000    2.000000    89.990000     179.970000
75%       10180.25000    3.000000   249.990000     399.225000
max       10240.00000   10.000000  3899.990000    3899.990000